### PR TITLE
[MTDSA-6156] Amend Foreign Property Income & Expenditure Period Summary parser & validator

### PR DESCRIPTION
**Pull request by james-work-account**

### CODE REVIEW

**Comment by Mbrookesy** [comment]
A little comment for generally, wouldn't using the names `AmendRequestParser` , `AmendRawData` etc be too broad of names incase there are other amend endpoints in the future?

**Comment by james-work-account** [comment]
> A little comment for generally, wouldn't using the names `AmendRequestParser` , `AmendRawData` etc be too broad of names incase there are other amend endpoints in the future?

@Mbrookesy Possibly, yeah. What do you think it should be changed to?

**Comment by Mbrookesy** [comment]
> > A little comment for generally, wouldn't using the names `AmendRequestParser` , `AmendRawData` etc be too broad of names incase there are other amend endpoints in the future?
> 
> @Mbrookesy Possibly, yeah. What do you think it should be changed to?

I would say either AmendForeignProperty or to be even more specific AmendForeignPropertyIncomeExpesesPeriodSummary though may be a bit long

**Comment by Thepworth95** [comment]
> > > A little comment for generally, wouldn't using the names `AmendRequestParser` , `AmendRawData` etc be too broad of names incase there are other amend endpoints in the future?
> > 
> > 
> > @Mbrookesy Possibly, yeah. What do you think it should be changed to?
> 
> I would say either AmendForeignProperty or to be even more specific AmendForeignPropertyIncomeExpesesPeriodSummary though may be a bit long

I've been using CreateForeignProperty and now AmendForeignProperty

**Comment by james-work-account** [comment]
> > > > A little comment for generally, wouldn't using the names `AmendRequestParser` , `AmendRawData` etc be too broad of names incase there are other amend endpoints in the future?
> > > 
> > > 
> > > @Mbrookesy Possibly, yeah. What do you think it should be changed to?
> > 
> > 
> > I would say either AmendForeignProperty or to be even more specific AmendForeignPropertyIncomeExpesesPeriodSummary though may be a bit long
> 
> I've been using CreateForeignProperty and now AmendForeignProperty

@Thepworth95 I'll change it all to AmendForeignProperty then 🤙🏼

**Pull request merged**
